import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';

const buildOut = resolve('src/build.ts');
const src = resolve('src/frontend/tailwind.src.css');
const twOut = resolve('src/frontend/tailwind.gen.ts');
const adminOut = resolve('src/frontend/admin.gen.ts');

function writeBuildID() {
  const id = new Date().toISOString().replace(/[:.]/g, '-');
  writeFileSync(buildOut, `// auto-generated by build, do not edit
export const BUILD_ID = ${JSON.stringify(id)};
`);
  console.log('✓ BUILD_ID:', id);
}

async function buildCSS() {
  const { compile } = await import('@tailwindcss/node');
  const { Scanner } = await import('@tailwindcss/oxide');

  const css = readFileSync(src, 'utf8');

  const deps: string[] = [];
  const design = await compile(css, {
    base: dirname(src) + '/',
    onDependency: (f: string) => deps.push(f),
  });

  const sources = [
    { base: resolve('src/frontend/'), pattern: '**/*.{ts,tsx}', negated: false },
  ];

  const scanner = new Scanner({ sources });
  const candidates = scanner.scan();

  const compiled = design.build(candidates);
  writeFileSync(twOut, `// auto-generated by build-css, do not edit
export const tailwindCSS: string = ${JSON.stringify(compiled)};
`);

  console.log('✓ CSS built (' + (compiled.length / 1024).toFixed(1) + ' KB, ' + candidates.length + ' candidates)');
}

async function buildAdminSPA() {
  const esbuild = await import('esbuild');
  const result = await esbuild.build({
    entryPoints: [resolve('src/frontend/index.tsx')],
    bundle: true,
    format: 'iife',
    jsx: 'automatic',
    write: false,
    minify: true,
    alias: { '@': resolve('src') },
  });
  const jsCode = result.outputFiles[0].text;

  const twContent = readFileSync(twOut, 'utf8');
  const twStart = twContent.indexOf('= ') + 2;
  const twEnd = twContent.lastIndexOf(';');
  const tailwindCSS = JSON.parse(twContent.slice(twStart, twEnd));

  const LANG_SCRIPT = '(function(){var l=localStorage.getItem("locale");if(l==="zh"||l==="en"){document.documentElement.lang=l;var c="locale="+l+";Path=/;SameSite=Lax";document.cookie=c;}else{var n=navigator.language||"";var d=n.startsWith("zh")?"zh":"en";localStorage.setItem("locale",d);document.documentElement.lang=d;}})()';

  const html = '<!DOCTYPE html><html lang="zh-CN"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><link rel="icon" href="/favicon.ico"/><title>CF ShortURL</title><style>' + tailwindCSS + '</style></head><body><div id="root"></div><script>' + LANG_SCRIPT + '</script><script>' + jsCode + '</script></body></html>';

  writeFileSync(adminOut, `// auto-generated by build-css, do not edit
export const adminHTML: string = ${JSON.stringify(html)};
`);

  console.log('✓ SPA built (' + (jsCode.length / 1024).toFixed(1) + ' KB JS, ' + (html.length / 1024).toFixed(1) + ' KB total)');
}

async function build() {
  writeBuildID();
  await buildCSS();
  await buildAdminSPA();
}

build().catch(err => {
  console.error('✗ Build failed:', err.message);
  if (!existsSync(twOut)) {
    writeFileSync(twOut, `// auto-generated fallback
export const tailwindCSS: string = '';
`);
    console.log('  wrote empty tailwind fallback');
  }
  if (!existsSync(adminOut)) {
    writeFileSync(adminOut, `// auto-generated fallback
export const adminHTML: string = '';
`);
    console.log('  wrote empty admin HTML fallback');
  }
  process.exit(1);
});
