import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';

const src = resolve('src/frontend/tailwind.src.css');
const twOut = resolve('src/frontend/tailwind.gen.ts');
const adminOut = resolve('src/frontend/admin.gen.ts');

async function buildCSS() {
  const { compile } = await import('@tailwindcss/node');
  const { Scanner } = await import('@tailwindcss/oxide');

  const css = readFileSync(src, 'utf8');

  const deps: string[] = [];
  const design = await compile(css, {
    base: dirname(src) + '/',
    onDependency: (f: string) => deps.push(f),
  });

  const sources = [
    { base: resolve('src/frontend/'), pattern: '**/*.{ts,tsx}', negated: false },
  ];

  const scanner = new Scanner({ sources });
  const candidates = scanner.scan();

  const compiled = design.build(candidates);
  writeFileSync(twOut, `// auto-generated by build-css, do not edit
export const tailwindCSS: string = ${JSON.stringify(compiled)};
`);

  console.log('✓ CSS built (' + (compiled.length / 1024).toFixed(1) + ' KB, ' + candidates.length + ' candidates)');
}

async function buildAdminSPA() {
  const esbuild = await import('esbuild');
  const result = await esbuild.build({
    entryPoints: [resolve('src/frontend/index.tsx')],
    bundle: true,
    format: 'iife',
    jsx: 'automatic',
    write: false,
    minify: true,
  });
  const jsCode = result.outputFiles[0].text;

  const twContent = readFileSync(twOut, 'utf8');
  const twStart = twContent.indexOf('= ') + 2;
  const twEnd = twContent.lastIndexOf(';');
  const tailwindCSS = JSON.parse(twContent.slice(twStart, twEnd));

  const customCSS = readFileSync(resolve('src/frontend/custom.css'), 'utf8');

  const html = '<!DOCTYPE html><html lang="zh-CN"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>CF ShortURL</title><style>' + tailwindCSS + '</style><style>' + customCSS + '</style></head><body><div id="root"></div><script>' + jsCode + '</script></body></html>';

  writeFileSync(adminOut, `// auto-generated by build-css, do not edit
export const adminHTML: string = ${JSON.stringify(html)};
`);

  console.log('✓ SPA built (' + (jsCode.length / 1024).toFixed(1) + ' KB JS, ' + (html.length / 1024).toFixed(1) + ' KB total)');
}

async function build() {
  await buildCSS();
  await buildAdminSPA();
}

build().catch(err => {
  console.error('✗ Build failed:', err.message);
  if (!existsSync(twOut)) {
    writeFileSync(twOut, `// auto-generated fallback
export const tailwindCSS: string = '';
`);
    console.log('  wrote empty tailwind fallback');
  }
  if (!existsSync(adminOut)) {
    writeFileSync(adminOut, `// auto-generated fallback
export const adminHTML: string = '';
`);
    console.log('  wrote empty admin HTML fallback');
  }
  process.exit(1);
});
